export const SET_LOADING = "SET_LOADING";
export const SET_SUCCESS = "SET_SUCCESS";
export const SET_FAILED = "SET_FAILED";
export const RECEIVE_CATEGORY_PRODUCT = "RECEIVE_CATEGORY_PRODUCT";
export const RECEIVE_BRANDS_PRODUCT = "RECEIVE_BRANDS_PRODUCT";