# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lunadorii' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for lunadorii
  # pod 'GoogleSignIn', '~> 4.3'

  target 'lunadoriiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'lunadorii-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for lunadorii-tvOS

  target 'lunadorii-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
