// export const API_SERVER='http://fc68a8d2.ngrok.io/'
export const API_SERVER_AUTH = 'http://6d2bb007.ngrok.io'
export const API_SERVER_USER = 'http://5968e53e.ngrok.io'
export const API_SERVER_PRODUCT='http://bb83b3b2.ngrok.io'
export const API_SERVER_BANNERS='http://9db0cebd.ngrok.io'