// export const API_SERVER='http://fc68a8d2.ngrok.io/'
export const API_SERVER_AUTH = 'http://26d10a4c.ngrok.io'
export const API_SERVER_USER = 'http://4f430a0f.ngrok.io'
export const API_SERVER_PRODUCT='http://0c3e7109.ngrok.io'
export const API_SERVER_BANNERS='http://7ca76209.ngrok.io'