// export const API_SERVER='http://fc68a8d2.ngrok.io/'
export const API_SERVER_AUTH = 'http://b7940e82.ngrok.io'
export const API_SERVER_USER = 'http://d72160f3.ngrok.io'
export const API_SERVER_PRODUCT='http://d798a5f7.ngrok.io'
export const API_SERVER_BANNERS='http://d3541e72.ngrok.io'